// Generated by design-sync — named re-exports for default-exported components,
// so the synth `export *` bundle entry (which drops defaults) still surfaces
// them on window.MyFridge. Wired via cfg.extraEntries. Safe to delete/regenerate.
export { default as AddStorageAreaDialog } from '@/components/AddStorageAreaDialog';
export { default as AddStoredItemDialog } from '@/components/AddStoredItemDialog';
export { default as BarcodeDisplay } from '@/components/BarcodeDisplay';
export { default as BarcodeScanner } from '@/components/BarcodeScanner';
export { default as BottomNavigation } from '@/components/BottomNavigation';
export { default as BrandLogo } from '@/components/BrandLogo';
export { default as LoyaltyCardForm } from '@/components/LoyaltyCardForm';
export { default as NotificationDrawer } from '@/components/NotificationDrawer';
export { default as StorageAreaCard } from '@/components/StorageAreaCard';
export { default as StorageAreaDialog } from '@/components/StorageAreaDialog';
export { default as StorageAreaManager } from '@/components/StorageAreaManager';
export { default as StoreSelector } from '@/components/StoreSelector';
export { default as AppShell } from '@/components/layout/AppShell';
export { default as NotificationSheet } from '@/components/layout/NotificationSheet';
export { default as LeftoverPortionsDialog } from '@/components/meals/LeftoverPortionsDialog';
export { default as AisleSection } from '@/components/shopping/AisleSection';
export { default as ShoppingBarcodeScanner } from '@/components/shopping/ShoppingBarcodeScanner';
export { default as ShoppingItemRow } from '@/components/shopping/ShoppingItemRow';
export { default as ShoppingViewModeToggle } from '@/components/shopping/ShoppingViewModeToggle';
// Preview harness provider: wraps every card so useNavigate()/useLocation() from
// react-router resolve (many components read router context). cfg.provider.
export { MemoryRouter } from 'react-router-dom';
// Form previews must use the bundle's single react-hook-form instance (a 2nd
// copy imported in a preview has an incompatible control). Re-export the hooks.
export { useForm, useFormContext, Controller, FormProvider } from 'react-hook-form';
