name: Deploy to Production Environment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy"
        required: false
        default: "latest"

jobs:
  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: http://my-fridge.multiplus.ovh:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Raspberry Pi
        run: |
          ssh ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "
            cd ~/Desktop/my-fridge &&
            git pull origin main &&
            docker compose down &&
            docker compose up -d --build
          "